version: '{build}'

image: Visual Studio 2017

skip_tags: true

only_commits:
  files:
    - '**/windows/**'
    - '**/util/**'

environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk11

init:
  - git config --global --unset core.autocrlf

install:
  - mvn --version
  - java -version

build_script:
  - appveyor-retry mvn clean package -Dmaven.test.skip=true

test_script:
  - mvn test
